Repository cmulay/DSA101, pull requests merged in 2021-06, with the labels that each got.

#5 Added Searching and sorting algorithms Python
  python/searching-algorithms/binary_search.py
  python/searching-algorithms/linear_search.py
  python/sorting-algorithms/bubble_sort.py
  python/sorting-algorithms/insertion_sort.py
  python/sorting-algorithms/merge_sort.py
  python/sorting-algorithms/quick_sort.py
  python/sorting-algorithms/selection_sort.py
Labels: enhancement, good first issue

#6 added linked list in python
  Python/data-structures/Linked_List.py
Labels: enhancement

#7 add stack in CPP
  CPP/Problems/valid_parentheses.cpp
  CPP/data-structures/stack.cpp
Labels: cpp
